sony: Add duchamp vendor on soong
error: vendor/sony/dolby/Android.bp:27:1: "libcodec2_soft_ddpdec" depends on undefined module "libcodec2_store_dolby".
Module "libcodec2_soft_ddpdec" is defined in namespace "vendor/sony/dolby" which can read these 2 namespaces: ["vendor/sony/dolby" "."]
Module "libcodec2_store_dolby" can be found in these namespaces: ["vendor/xiaomi/duchamp"]
Or did you mean ["//libcore/benchmarks" "//libcore/expectations" "//libcore/luni/src/test" "//libcore/toolchainapi" "codec2_core_param_test"]?
error: vendor/sony/dolby/Android.bp:10:1: "libcodec2_soft_ac4dec" depends on undefined module "libcodec2_store_dolby".
Module "libcodec2_soft_ac4dec" is defined in namespace "vendor/sony/dolby" which can read these 2 namespaces: ["vendor/sony/dolby" "."]
Module "libcodec2_store_dolby" can be found in these namespaces: ["vendor/xiaomi/duchamp"]
Or did you mean ["//libcore/benchmarks" "//libcore/expectations" "//libcore/luni/src/test" "//libcore/toolchainapi" "codec2_core_param_test"]?
01:26:35 soong bootstrap failed with: exit status 1

Signed-off-by: zenin1504 <kayozzprojects@yandex.com>